services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # Используем порт 5433 чтобы не конфликтовать с локальным PostgreSQL

  web:
    build: .
    command: >
      sh -c "sleep 3 &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      # Простые переменные
      DJANGO_SETTINGS_MODULE: config.settings
      DEBUG: "True"
      SECRET_KEY: "test123"
    depends_on:
      - db
