[project]
name = "hotel-booking-django"
version = "0.1.0"
description = ""
authors = [
    {name = "Rulet63",email = "davletov2106@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django (>=6.0,<7.0)",
    "djangorestframework (>=3.16.1,<4.0.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "psycopg2-binary (>=2.9.11,<3.0.0)",
    "django-filter (>=25.2,<26.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ruff = "^0.14.9"
pre-commit = "^4.5.1"
pytest = "^9.0.2"
pytest-django = "^4.11.1"
pytest-cov = "^7.0.0"

